const bibleReadingPlan = [
 {
   "Week": 1,
   "NT Book": "1 John",
   "NT Ch.": "",
   "OT Book": "Genesis",
   "OT Ch.": "1-5",
   "Psalms": "Psalms",
   "Ps Ch.": "1-2",
   "Proverbs": "Proverbs",
   "Prov Ch.": 1
 },
 {
   "Week": 2,
   "NT Book": "John",
   "NT Ch.": "1-4",
   "OT Book": "Genesis",
   "OT Ch.": "6-8",
   "Psalms": "Psalms",
   "Ps Ch.": "3-4",
   "Proverbs": "Proverbs",
   "Prov Ch.": 2
 },
 {
   "Week": 3,
   "NT Book": "John",
   "NT Ch.": "5-8",
   "OT Book": "Genesis",
   "OT Ch.": "9-11",
   "Psalms": "Psalms",
   "Ps Ch.": "5-7",
   "Proverbs": "Proverbs",
   "Prov Ch.": 3
 },
 {
   "Week": 4,
   "NT Book": "John",
   "NT Ch.": "9-12",
   "OT Book": "Genesis",
   "OT Ch.": "12-16",
   "Psalms": "Psalms",
   "Ps Ch.": "8-9",
   "Proverbs": "Proverbs",
   "Prov Ch.": 4
 },
 {
   "Week": 5,
   "NT Book": "John",
   "NT Ch.": "13-17",
   "OT Book": "Genesis",
   "OT Ch.": "17-20",
   "Psalms": "Psalms",
   "Ps Ch.": "10-11",
   "Proverbs": "Proverbs",
   "Prov Ch.": 5
 },
 {
   "Week": 6,
   "NT Book": "John",
   "NT Ch.": "18-21",
   "OT Book": "Genesis",
   "OT Ch.": "21-24",
   "Psalms": "Psalms",
   "Ps Ch.": "12-14",
   "Proverbs": "Proverbs",
   "Prov Ch.": 6
 },
 {
   "Week": 7,
   "NT Book": "Philippians",
   "NT Ch.": "",
   "OT Book": "Genesis",
   "OT Ch.": "25-28",
   "Psalms": "Psalms",
   "Ps Ch.": "15-16",
   "Proverbs": "Proverbs",
   "Prov Ch.": 7
 },
 {
   "Week": 8,
   "NT Book": "Matthew",
   "NT Ch.": "1-4",
   "OT Book": "Genesis",
   "OT Ch.": "29-33",
   "Psalms": "Psalms",
   "Ps Ch.": "17-18",
   "Proverbs": "Proverbs",
   "Prov Ch.": 8
 },
 {
   "Week": 9,
   "NT Book": "Matthew",
   "NT Ch.": "5-8",
   "OT Book": "Genesis",
   "OT Ch.": "34-38",
   "Psalms": "Psalms",
   "Ps Ch.": "19-21",
   "Proverbs": "Proverbs",
   "Prov Ch.": 9
 },
 {
   "Week": 10,
   "NT Book": "Matthew",
   "NT Ch.": "9-12",
   "OT Book": "Genesis",
   "OT Ch.": "39-45",
   "Psalms": "Psalms",
   "Ps Ch.": "22-23",
   "Proverbs": "Proverbs",
   "Prov Ch.": 10
 },
 {
   "Week": 11,
   "NT Book": "Matthew",
   "NT Ch.": "13-16",
   "OT Book": "Genesis",
   "OT Ch.": "46-50",
   "Psalms": "Psalms",
   "Ps Ch.": "24-25",
   "Proverbs": "Proverbs",
   "Prov Ch.": 11
 },
 {
   "Week": 12,
   "NT Book": "Matthew",
   "NT Ch.": "17-20",
   "OT Book": "Exodus",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "26-28",
   "Proverbs": "Proverbs",
   "Prov Ch.": 12
 },
 {
   "Week": 13,
   "NT Book": "Matthew",
   "NT Ch.": "21-24",
   "OT Book": "Exodus",
   "OT Ch.": "5-9",
   "Psalms": "Psalms",
   "Ps Ch.": "29-30",
   "Proverbs": "Proverbs",
   "Prov Ch.": 13
 },
 {
   "Week": 14,
   "NT Book": "Matthew",
   "NT Ch.": "25-28",
   "OT Book": "Exodus",
   "OT Ch.": "10-14",
   "Psalms": "Psalms",
   "Ps Ch.": "31-32",
   "Proverbs": "Proverbs",
   "Prov Ch.": 14
 },
 {
   "Week": 15,
   "NT Book": "Colossians",
   "NT Ch.": "",
   "OT Book": "Exodus",
   "OT Ch.": "15-18",
   "Psalms": "Psalms",
   "Ps Ch.": "33-35",
   "Proverbs": "Proverbs",
   "Prov Ch.": 15
 },
 {
   "Week": 16,
   "NT Book": "Acts",
   "NT Ch.": "1-4",
   "OT Book": "Exodus",
   "OT Ch.": "19-23",
   "Psalms": "Psalms",
   "Ps Ch.": "36-37",
   "Proverbs": "Proverbs",
   "Prov Ch.": 16
 },
 {
   "Week": 17,
   "NT Book": "Acts",
   "NT Ch.": "5-8",
   "OT Book": "Exodus",
   "OT Ch.": "24-27",
   "Psalms": "Psalms",
   "Ps Ch.": "38-39",
   "Proverbs": "Proverbs",
   "Prov Ch.": 17
 },
 {
   "Week": 18,
   "NT Book": "Acts",
   "NT Ch.": "9-12",
   "OT Book": "Exodus",
   "OT Ch.": "28-31",
   "Psalms": "Psalms",
   "Ps Ch.": "40-42",
   "Proverbs": "Proverbs",
   "Prov Ch.": 18
 },
 {
   "Week": 19,
   "NT Book": "Acts",
   "NT Ch.": "13-16",
   "OT Book": "Exodus",
   "OT Ch.": "32-35",
   "Psalms": "Psalms",
   "Ps Ch.": "43-44",
   "Proverbs": "Proverbs",
   "Prov Ch.": 19
 },
 {
   "Week": 20,
   "NT Book": "Acts",
   "NT Ch.": "17-20",
   "OT Book": "Exodus",
   "OT Ch.": "36-40",
   "Psalms": "Psalms",
   "Ps Ch.": "45-46",
   "Proverbs": "Proverbs",
   "Prov Ch.": 20
 },
 {
   "Week": 21,
   "NT Book": "Acts",
   "NT Ch.": "21-24",
   "OT Book": "Leviticus",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "47-49",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 22,
   "NT Book": "Acts",
   "NT Ch.": "25-28",
   "OT Book": "Leviticus",
   "OT Ch.": "4-7",
   "Psalms": "Psalms",
   "Ps Ch.": "50-51",
   "Proverbs": "Proverbs",
   "Prov Ch.": 21
 },
 {
   "Week": 23,
   "NT Book": "2 John",
   "NT Ch.": "",
   "OT Book": "Leviticus",
   "OT Ch.": "8-10",
   "Psalms": "Psalms",
   "Ps Ch.": "52-53",
   "Proverbs": "Proverbs",
   "Prov Ch.": 22
 },
 {
   "Week": 24,
   "NT Book": "Galatians",
   "NT Ch.": "",
   "OT Book": "Leviticus",
   "OT Ch.": "11-14",
   "Psalms": "Psalms",
   "Ps Ch.": "54-56",
   "Proverbs": "Proverbs",
   "Prov Ch.": 23
 },
 {
   "Week": 25,
   "NT Book": "3 John",
   "NT Ch.": "",
   "OT Book": "Leviticus",
   "OT Ch.": "15-17",
   "Psalms": "Psalms",
   "Ps Ch.": "57-58",
   "Proverbs": "Proverbs",
   "Prov Ch.": 24
 },
 {
   "Week": 26,
   "NT Book": "Romans",
   "NT Ch.": "1-4",
   "OT Book": "Leviticus",
   "OT Ch.": "18-20",
   "Psalms": "Psalms",
   "Ps Ch.": "59-60",
   "Proverbs": "Proverbs",
   "Prov Ch.": 25
 },
 {
   "Week": 27,
   "NT Book": "Romans",
   "NT Ch.": "5-8",
   "OT Book": "Leviticus",
   "OT Ch.": "21-24",
   "Psalms": "Psalms",
   "Ps Ch.": "61-63",
   "Proverbs": "Proverbs",
   "Prov Ch.": 26
 },
 {
   "Week": 28,
   "NT Book": "Romans",
   "NT Ch.": "9-12",
   "OT Book": "Leviticus",
   "OT Ch.": "25-27",
   "Psalms": "Psalms",
   "Ps Ch.": "64-65",
   "Proverbs": "Proverbs",
   "Prov Ch.": 27
 },
 {
   "Week": 29,
   "NT Book": "Romans",
   "NT Ch.": "13-16",
   "OT Book": "Numbers",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "66-67",
   "Proverbs": "Proverbs",
   "Prov Ch.": 28
 },
 {
   "Week": 30,
   "NT Book": "Ephesians",
   "NT Ch.": "",
   "OT Book": "Numbers",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "68-70",
   "Proverbs": "Proverbs",
   "Prov Ch.": 29
 },
 {
   "Week": 31,
   "NT Book": "Mark",
   "NT Ch.": "1-4",
   "OT Book": "Numbers",
   "OT Ch.": "9-12",
   "Psalms": "Psalms",
   "Ps Ch.": "71-72",
   "Proverbs": "Proverbs",
   "Prov Ch.": 30
 },
 {
   "Week": 32,
   "NT Book": "Mark",
   "NT Ch.": "5-8",
   "OT Book": "Numbers",
   "OT Ch.": "13-16",
   "Psalms": "Psalms",
   "Ps Ch.": "73-74",
   "Proverbs": "Proverbs",
   "Prov Ch.": 31
 },
 {
   "Week": 33,
   "NT Book": "Mark",
   "NT Ch.": "9-12",
   "OT Book": "Numbers",
   "OT Ch.": "17-20",
   "Psalms": "Psalms",
   "Ps Ch.": "75-76",
   "Proverbs": "Proverbs",
   "Prov Ch.": 1
 },
 {
   "Week": 34,
   "NT Book": "Mark",
   "NT Ch.": "13-16",
   "OT Book": "Numbers",
   "OT Ch.": "21-24",
   "Psalms": "Psalms",
   "Ps Ch.": "77-78",
   "Proverbs": "Proverbs",
   "Prov Ch.": 2
 },
 {
   "Week": 35,
   "NT Book": "James",
   "NT Ch.": "",
   "OT Book": "Numbers",
   "OT Ch.": "25-28",
   "Psalms": "Psalms",
   "Ps Ch.": "79-80",
   "Proverbs": "Proverbs",
   "Prov Ch.": 3
 },
 {
   "Week": 36,
   "NT Book": "1 Corinthians",
   "NT Ch.": "1-4",
   "OT Book": "Numbers",
   "OT Ch.": "29-32",
   "Psalms": "Psalms",
   "Ps Ch.": "81-83",
   "Proverbs": "Proverbs",
   "Prov Ch.": 4
 },
 {
   "Week": 37,
   "NT Book": "1 Corinthians",
   "NT Ch.": "5-8",
   "OT Book": "Numbers",
   "OT Ch.": "33-36",
   "Psalms": "Psalms",
   "Ps Ch.": "84-85",
   "Proverbs": "Proverbs",
   "Prov Ch.": 5
 },
 {
   "Week": 38,
   "NT Book": "1 Corinthians",
   "NT Ch.": "9-12",
   "OT Book": "Deuteronomy",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "86-87",
   "Proverbs": "Proverbs",
   "Prov Ch.": 6
 },
 {
   "Week": 39,
   "NT Book": "1 Corinthians",
   "NT Ch.": "13-16",
   "OT Book": "Deuteronomy",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "88-90",
   "Proverbs": "Proverbs",
   "Prov Ch.": 7
 },
 {
   "Week": 40,
   "NT Book": "1 Thessalonians",
   "NT Ch.": "",
   "OT Book": "Deuteronomy",
   "OT Ch.": "9-13",
   "Psalms": "Psalms",
   "Ps Ch.": "91-92",
   "Proverbs": "Proverbs",
   "Prov Ch.": 8
 },
 {
   "Week": 41,
   "NT Book": "2 Corinthians",
   "NT Ch.": "1-4",
   "OT Book": "Deuteronomy",
   "OT Ch.": "14-18",
   "Psalms": "Psalms",
   "Ps Ch.": "93-94",
   "Proverbs": "Proverbs",
   "Prov Ch.": 9
 },
 {
   "Week": 42,
   "NT Book": "2 Corinthians",
   "NT Ch.": "5-9",
   "OT Book": "Deuteronomy",
   "OT Ch.": "19-22",
   "Psalms": "Psalms",
   "Ps Ch.": "95-97",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 43,
   "NT Book": "2 Corinthians",
   "NT Ch.": "10-13",
   "OT Book": "Deuteronomy",
   "OT Ch.": "23-26",
   "Psalms": "Psalms",
   "Ps Ch.": "98-99",
   "Proverbs": "Proverbs",
   "Prov Ch.": 10
 },
 {
   "Week": 44,
   "NT Book": "2 Thessalonians",
   "NT Ch.": "",
   "OT Book": "Deuteronomy",
   "OT Ch.": "27-30",
   "Psalms": "Psalms",
   "Ps Ch.": "100-101",
   "Proverbs": "Proverbs",
   "Prov Ch.": 11
 },
 {
   "Week": 45,
   "NT Book": "Luke",
   "NT Ch.": "1-4",
   "OT Book": "Deuteronomy",
   "OT Ch.": "31-34",
   "Psalms": "Psalms",
   "Ps Ch.": "102-104",
   "Proverbs": "Proverbs",
   "Prov Ch.": 12
 },
 {
   "Week": 46,
   "NT Book": "Luke",
   "NT Ch.": "5-8",
   "OT Book": "Joshua",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "105-106",
   "Proverbs": "Proverbs",
   "Prov Ch.": 13
 },
 {
   "Week": 47,
   "NT Book": "Luke",
   "NT Ch.": "9-12",
   "OT Book": "Joshua",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "107-108",
   "Proverbs": "Proverbs",
   "Prov Ch.": 14
 },
 {
   "Week": 48,
   "NT Book": "Luke",
   "NT Ch.": "13-16",
   "OT Book": "Joshua",
   "OT Ch.": "9-12",
   "Psalms": "Psalms",
   "Ps Ch.": "109-111",
   "Proverbs": "Proverbs",
   "Prov Ch.": 15
 },
 {
   "Week": 49,
   "NT Book": "Luke",
   "NT Ch.": "17-20",
   "OT Book": "Joshua",
   "OT Ch.": "13-17",
   "Psalms": "Psalms",
   "Ps Ch.": "112-113",
   "Proverbs": "Proverbs",
   "Prov Ch.": 16
 },
 {
   "Week": 50,
   "NT Book": "Luke",
   "NT Ch.": "21-24",
   "OT Book": "Joshua",
   "OT Ch.": "18-21",
   "Psalms": "Psalms",
   "Ps Ch.": "114-115",
   "Proverbs": "Proverbs",
   "Prov Ch.": 17
 },
 {
   "Week": 51,
   "NT Book": "1 Timothy",
   "NT Ch.": "",
   "OT Book": "Joshua",
   "OT Ch.": "22-24",
   "Psalms": "Psalms",
   "Ps Ch.": "116-118",
   "Proverbs": "Proverbs",
   "Prov Ch.": 18
 },
 {
   "Week": 52,
   "NT Book": "Hebrews",
   "NT Ch.": "1-4",
   "OT Book": "Judges",
   "OT Ch.": "1-5",
   "Psalms": "Psalms",
   "Ps Ch.": "119-120",
   "Proverbs": "Proverbs",
   "Prov Ch.": 19
 },
 {
   "Week": 53,
   "NT Book": "Hebrews",
   "NT Ch.": "5-8",
   "OT Book": "Judges",
   "OT Ch.": "6-9",
   "Psalms": "Psalms",
   "Ps Ch.": "121-122",
   "Proverbs": "Proverbs",
   "Prov Ch.": 20
 },
 {
   "Week": 54,
   "NT Book": "Hebrews",
   "NT Ch.": "9-13",
   "OT Book": "Judges",
   "OT Ch.": "10-12",
   "Psalms": "Psalms",
   "Ps Ch.": "123-125",
   "Proverbs": "Proverbs",
   "Prov Ch.": 21
 },
 {
   "Week": 55,
   "NT Book": "2 Timothy",
   "NT Ch.": "",
   "OT Book": "Judges",
   "OT Ch.": "13-16",
   "Psalms": "Psalms",
   "Ps Ch.": "126-127",
   "Proverbs": "Proverbs",
   "Prov Ch.": 22
 },
 {
   "Week": 56,
   "NT Book": "Titus",
   "NT Ch.": "",
   "OT Book": "Judges",
   "OT Ch.": "17-21",
   "Psalms": "Psalms",
   "Ps Ch.": "128-129",
   "Proverbs": "Proverbs",
   "Prov Ch.": 23
 },
 {
   "Week": 57,
   "NT Book": "Revelation",
   "NT Ch.": "1-5",
   "OT Book": "Ruth",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "130-132",
   "Proverbs": "Proverbs",
   "Prov Ch.": 24
 },
 {
   "Week": 58,
   "NT Book": "Revelation",
   "NT Ch.": "6-9",
   "OT Book": "1 Samuel",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "133-134",
   "Proverbs": "Proverbs",
   "Prov Ch.": 25
 },
 {
   "Week": 59,
   "NT Book": "Revelation",
   "NT Ch.": "10-14",
   "OT Book": "1 Samuel",
   "OT Ch.": "4-7",
   "Psalms": "Psalms",
   "Ps Ch.": "135-136",
   "Proverbs": "Proverbs",
   "Prov Ch.": 26
 },
 {
   "Week": 60,
   "NT Book": "Revelation",
   "NT Ch.": "15-18",
   "OT Book": "1 Samuel",
   "OT Ch.": "8-12",
   "Psalms": "Psalms",
   "Ps Ch.": "137-139",
   "Proverbs": "Proverbs",
   "Prov Ch.": 27
 },
 {
   "Week": 61,
   "NT Book": "Revelation",
   "NT Ch.": "19-22",
   "OT Book": "1 Samuel",
   "OT Ch.": "13-16",
   "Psalms": "Psalms",
   "Ps Ch.": "140-141",
   "Proverbs": "Proverbs",
   "Prov Ch.": 28
 },
 {
   "Week": 62,
   "NT Book": "1 Peter",
   "NT Ch.": "",
   "OT Book": "1 Samuel",
   "OT Ch.": "17-20",
   "Psalms": "Psalms",
   "Ps Ch.": "142-143",
   "Proverbs": "Proverbs",
   "Prov Ch.": 29
 },
 {
   "Week": 63,
   "NT Book": "Philemon",
   "NT Ch.": "",
   "OT Book": "1 Samuel",
   "OT Ch.": "21-24",
   "Psalms": "Psalms",
   "Ps Ch.": "144-145",
   "Proverbs": "Proverbs",
   "Prov Ch.": 30
 },
 {
   "Week": 64,
   "NT Book": "2 Peter",
   "NT Ch.": "",
   "OT Book": "1 Samuel",
   "OT Ch.": "25-28",
   "Psalms": "Psalms",
   "Ps Ch.": "146-148",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 65,
   "NT Book": "Jude",
   "NT Ch.": "",
   "OT Book": "1 Samuel",
   "OT Ch.": "29-31",
   "Psalms": "Psalms",
   "Ps Ch.": "149-150",
   "Proverbs": "Proverbs",
   "Prov Ch.": 31
 },
 {
   "Week": 66,
   "NT Book": "1 John",
   "NT Ch.": "",
   "OT Book": "2 Samuel",
   "OT Ch.": "1-5",
   "Psalms": "Psalms",
   "Ps Ch.": "1-2",
   "Proverbs": "Proverbs",
   "Prov Ch.": 1
 },
 {
   "Week": 67,
   "NT Book": "John",
   "NT Ch.": "1-4",
   "OT Book": "2 Samuel",
   "OT Ch.": "6-10",
   "Psalms": "Psalms",
   "Ps Ch.": "3-4",
   "Proverbs": "Proverbs",
   "Prov Ch.": 2
 },
 {
   "Week": 68,
   "NT Book": "John",
   "NT Ch.": "5-8",
   "OT Book": "2 Samuel",
   "OT Ch.": "11-13",
   "Psalms": "Psalms",
   "Ps Ch.": "5-7",
   "Proverbs": "Proverbs",
   "Prov Ch.": 3
 },
 {
   "Week": 69,
   "NT Book": "John",
   "NT Ch.": "9-12",
   "OT Book": "2 Samuel",
   "OT Ch.": "14-17",
   "Psalms": "Psalms",
   "Ps Ch.": "8-9",
   "Proverbs": "Proverbs",
   "Prov Ch.": 4
 },
 {
   "Week": 70,
   "NT Book": "John",
   "NT Ch.": "13-17",
   "OT Book": "2 Samuel",
   "OT Ch.": "18-20",
   "Psalms": "Psalms",
   "Ps Ch.": "10-11",
   "Proverbs": "Proverbs",
   "Prov Ch.": 5
 },
 {
   "Week": 71,
   "NT Book": "John",
   "NT Ch.": "18-21",
   "OT Book": "2 Samuel",
   "OT Ch.": "21-24",
   "Psalms": "Psalms",
   "Ps Ch.": "12-14",
   "Proverbs": "Proverbs",
   "Prov Ch.": 6
 },
 {
   "Week": 72,
   "NT Book": "Philippians",
   "NT Ch.": "",
   "OT Book": "1 Kings",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "15-16",
   "Proverbs": "Proverbs",
   "Prov Ch.": 7
 },
 {
   "Week": 73,
   "NT Book": "Matthew",
   "NT Ch.": "1-4",
   "OT Book": "1 Kings",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "17-18",
   "Proverbs": "Proverbs",
   "Prov Ch.": 8
 },
 {
   "Week": 74,
   "NT Book": "Matthew",
   "NT Ch.": "5-8",
   "OT Book": "1 Kings",
   "OT Ch.": "9-11",
   "Psalms": "Psalms",
   "Ps Ch.": "19-21",
   "Proverbs": "Proverbs",
   "Prov Ch.": 9
 },
 {
   "Week": 75,
   "NT Book": "Matthew",
   "NT Ch.": "9-12",
   "OT Book": "1 Kings",
   "OT Ch.": "12-16",
   "Psalms": "Psalms",
   "Ps Ch.": "22-23",
   "Proverbs": "Proverbs",
   "Prov Ch.": 10
 },
 {
   "Week": 76,
   "NT Book": "Matthew",
   "NT Ch.": "13-16",
   "OT Book": "1 Kings",
   "OT Ch.": "17-19",
   "Psalms": "Psalms",
   "Ps Ch.": "24-25",
   "Proverbs": "Proverbs",
   "Prov Ch.": 11
 },
 {
   "Week": 77,
   "NT Book": "Matthew",
   "NT Ch.": "17-20",
   "OT Book": "1 Kings",
   "OT Ch.": "20-22",
   "Psalms": "Psalms",
   "Ps Ch.": "26-28",
   "Proverbs": "Proverbs",
   "Prov Ch.": 12
 },
 {
   "Week": 78,
   "NT Book": "Matthew",
   "NT Ch.": "21-24",
   "OT Book": "2 Kings",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "29-30",
   "Proverbs": "Proverbs",
   "Prov Ch.": 13
 },
 {
   "Week": 79,
   "NT Book": "Matthew",
   "NT Ch.": "25-28",
   "OT Book": "2 Kings",
   "OT Ch.": "4-7",
   "Psalms": "Psalms",
   "Ps Ch.": "31-32",
   "Proverbs": "Proverbs",
   "Prov Ch.": 14
 },
 {
   "Week": 80,
   "NT Book": "Colossians",
   "NT Ch.": "",
   "OT Book": "2 Kings",
   "OT Ch.": "8-10",
   "Psalms": "Psalms",
   "Ps Ch.": "33-35",
   "Proverbs": "Proverbs",
   "Prov Ch.": 15
 },
 {
   "Week": 81,
   "NT Book": "Acts",
   "NT Ch.": "1-4",
   "OT Book": "2 Kings",
   "OT Ch.": "11-14",
   "Psalms": "Psalms",
   "Ps Ch.": "36-37",
   "Proverbs": "Proverbs",
   "Prov Ch.": 16
 },
 {
   "Week": 82,
   "NT Book": "Acts",
   "NT Ch.": "5-8",
   "OT Book": "2 Kings",
   "OT Ch.": "15-17",
   "Psalms": "Psalms",
   "Ps Ch.": "38-39",
   "Proverbs": "Proverbs",
   "Prov Ch.": 17
 },
 {
   "Week": 83,
   "NT Book": "Acts",
   "NT Ch.": "9-12",
   "OT Book": "2 Kings",
   "OT Ch.": "18-21",
   "Psalms": "Psalms",
   "Ps Ch.": "40-42",
   "Proverbs": "Proverbs",
   "Prov Ch.": 18
 },
 {
   "Week": 84,
   "NT Book": "Acts",
   "NT Ch.": "13-16",
   "OT Book": "2 Kings",
   "OT Ch.": "22-25",
   "Psalms": "Psalms",
   "Ps Ch.": "43-44",
   "Proverbs": "Proverbs",
   "Prov Ch.": 19
 },
 {
   "Week": 85,
   "NT Book": "Acts",
   "NT Ch.": "17-20",
   "OT Book": "1 Chronicles",
   "OT Ch.": "1-5",
   "Psalms": "Psalms",
   "Ps Ch.": "45-46",
   "Proverbs": "Proverbs",
   "Prov Ch.": 20
 },
 {
   "Week": 86,
   "NT Book": "Acts",
   "NT Ch.": "21-24",
   "OT Book": "1 Chronicles",
   "OT Ch.": "6-9",
   "Psalms": "Psalms",
   "Ps Ch.": "47-49",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 87,
   "NT Book": "Acts",
   "NT Ch.": "25-28",
   "OT Book": "1 Chronicles",
   "OT Ch.": "10-12",
   "Psalms": "Psalms",
   "Ps Ch.": "50-51",
   "Proverbs": "Proverbs",
   "Prov Ch.": 21
 },
 {
   "Week": 88,
   "NT Book": "2 John",
   "NT Ch.": "",
   "OT Book": "1 Chronicles",
   "OT Ch.": "13-17",
   "Psalms": "Psalms",
   "Ps Ch.": "52-53",
   "Proverbs": "Proverbs",
   "Prov Ch.": 22
 },
 {
   "Week": 89,
   "NT Book": "Galatians",
   "NT Ch.": "",
   "OT Book": "1 Chronicles",
   "OT Ch.": "18-20",
   "Psalms": "Psalms",
   "Ps Ch.": "54-56",
   "Proverbs": "Proverbs",
   "Prov Ch.": 23
 },
 {
   "Week": 90,
   "NT Book": "3 John",
   "NT Ch.": "",
   "OT Book": "1 Chronicles",
   "OT Ch.": "21-25",
   "Psalms": "Psalms",
   "Ps Ch.": "57-58",
   "Proverbs": "Proverbs",
   "Prov Ch.": 24
 },
 {
   "Week": 91,
   "NT Book": "Romans",
   "NT Ch.": "1-4",
   "OT Book": "1 Chronicles",
   "OT Ch.": "26-29",
   "Psalms": "Psalms",
   "Ps Ch.": "59-60",
   "Proverbs": "Proverbs",
   "Prov Ch.": 25
 },
 {
   "Week": 92,
   "NT Book": "Romans",
   "NT Ch.": "5-8",
   "OT Book": "2 Chronicles",
   "OT Ch.": "1-5",
   "Psalms": "Psalms",
   "Ps Ch.": "61-63",
   "Proverbs": "Proverbs",
   "Prov Ch.": 26
 },
 {
   "Week": 93,
   "NT Book": "Romans",
   "NT Ch.": "9-12",
   "OT Book": "2 Chronicles",
   "OT Ch.": "6-9",
   "Psalms": "Psalms",
   "Ps Ch.": "64-65",
   "Proverbs": "Proverbs",
   "Prov Ch.": 27
 },
 {
   "Week": 94,
   "NT Book": "Romans",
   "NT Ch.": "13-16",
   "OT Book": "2 Chronicles",
   "OT Ch.": "10-13",
   "Psalms": "Psalms",
   "Ps Ch.": "66-67",
   "Proverbs": "Proverbs",
   "Prov Ch.": 28
 },
 {
   "Week": 95,
   "NT Book": "Ephesians",
   "NT Ch.": "",
   "OT Book": "2 Chronicles",
   "OT Ch.": "14-16",
   "Psalms": "Psalms",
   "Ps Ch.": "68-70",
   "Proverbs": "Proverbs",
   "Prov Ch.": 29
 },
 {
   "Week": 96,
   "NT Book": "Mark",
   "NT Ch.": "1-4",
   "OT Book": "2 Chronicles",
   "OT Ch.": "17-21",
   "Psalms": "Psalms",
   "Ps Ch.": "71-72",
   "Proverbs": "Proverbs",
   "Prov Ch.": 30
 },
 {
   "Week": 97,
   "NT Book": "Mark",
   "NT Ch.": "5-8",
   "OT Book": "2 Chronicles",
   "OT Ch.": "22-27",
   "Psalms": "Psalms",
   "Ps Ch.": "73-74",
   "Proverbs": "Proverbs",
   "Prov Ch.": 31
 },
 {
   "Week": 98,
   "NT Book": "Mark",
   "NT Ch.": "9-12",
   "OT Book": "2 Chronicles",
   "OT Ch.": "28-32",
   "Psalms": "Psalms",
   "Ps Ch.": "75-76",
   "Proverbs": "Proverbs",
   "Prov Ch.": 1
 },
 {
   "Week": 99,
   "NT Book": "Mark",
   "NT Ch.": "13-16",
   "OT Book": "2 Chronicles",
   "OT Ch.": "33-36",
   "Psalms": "Psalms",
   "Ps Ch.": "77-78",
   "Proverbs": "Proverbs",
   "Prov Ch.": 2
 },
 {
   "Week": 100,
   "NT Book": "James",
   "NT Ch.": "",
   "OT Book": "Ezra",
   "OT Ch.": "1-6",
   "Psalms": "Psalms",
   "Ps Ch.": "79-80",
   "Proverbs": "Proverbs",
   "Prov Ch.": 3
 },
 {
   "Week": 101,
   "NT Book": "1 Corinthians",
   "NT Ch.": "1-4",
   "OT Book": "Ezra",
   "OT Ch.": "7-10",
   "Psalms": "Psalms",
   "Ps Ch.": "81-83",
   "Proverbs": "Proverbs",
   "Prov Ch.": 4
 },
 {
   "Week": 102,
   "NT Book": "1 Corinthians",
   "NT Ch.": "5-8",
   "OT Book": "Nehemiah",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "84-85",
   "Proverbs": "Proverbs",
   "Prov Ch.": 5
 },
 {
   "Week": 103,
   "NT Book": "1 Corinthians",
   "NT Ch.": "9-12",
   "OT Book": "Nehemiah",
   "OT Ch.": "4-7",
   "Psalms": "Psalms",
   "Ps Ch.": "86-87",
   "Proverbs": "Proverbs",
   "Prov Ch.": 6
 },
 {
   "Week": 104,
   "NT Book": "1 Corinthians",
   "NT Ch.": "13-16",
   "OT Book": "Nehemiah",
   "OT Ch.": "8-10",
   "Psalms": "Psalms",
   "Ps Ch.": "88-90",
   "Proverbs": "Proverbs",
   "Prov Ch.": 7
 },
 {
   "Week": 105,
   "NT Book": "1 Thessalonians",
   "NT Ch.": "",
   "OT Book": "Nehemiah",
   "OT Ch.": "11-13",
   "Psalms": "Psalms",
   "Ps Ch.": "91-92",
   "Proverbs": "Proverbs",
   "Prov Ch.": 8
 },
 {
   "Week": 106,
   "NT Book": "2 Corinthians",
   "NT Ch.": "1-4",
   "OT Book": "Esther",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "93-94",
   "Proverbs": "Proverbs",
   "Prov Ch.": 9
 },
 {
   "Week": 107,
   "NT Book": "2 Corinthians",
   "NT Ch.": "5-9",
   "OT Book": "Esther",
   "OT Ch.": "5-10",
   "Psalms": "Psalms",
   "Ps Ch.": "95-97",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 108,
   "NT Book": "2 Corinthians",
   "NT Ch.": "10-13",
   "OT Book": "Job",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "98-99",
   "Proverbs": "Proverbs",
   "Prov Ch.": 10
 },
 {
   "Week": 109,
   "NT Book": "2 Thessalonians",
   "NT Ch.": "",
   "OT Book": "Job",
   "OT Ch.": "4-7",
   "Psalms": "Psalms",
   "Ps Ch.": "100-101",
   "Proverbs": "Proverbs",
   "Prov Ch.": 11
 },
 {
   "Week": 110,
   "NT Book": "Luke",
   "NT Ch.": "1-4",
   "OT Book": "Job",
   "OT Ch.": "8-10",
   "Psalms": "Psalms",
   "Ps Ch.": "102-104",
   "Proverbs": "Proverbs",
   "Prov Ch.": 12
 },
 {
   "Week": 111,
   "NT Book": "Luke",
   "NT Ch.": "5-8",
   "OT Book": "Job",
   "OT Ch.": "11-14",
   "Psalms": "Psalms",
   "Ps Ch.": "105-106",
   "Proverbs": "Proverbs",
   "Prov Ch.": 13
 },
 {
   "Week": 112,
   "NT Book": "Luke",
   "NT Ch.": "9-12",
   "OT Book": "Job",
   "OT Ch.": "15-17",
   "Psalms": "Psalms",
   "Ps Ch.": "107-108",
   "Proverbs": "Proverbs",
   "Prov Ch.": 14
 },
 {
   "Week": 113,
   "NT Book": "Luke",
   "NT Ch.": "13-16",
   "OT Book": "Job",
   "OT Ch.": "18-21",
   "Psalms": "Psalms",
   "Ps Ch.": "109-111",
   "Proverbs": "Proverbs",
   "Prov Ch.": 15
 },
 {
   "Week": 114,
   "NT Book": "Luke",
   "NT Ch.": "17-20",
   "OT Book": "Job",
   "OT Ch.": "22-26",
   "Psalms": "Psalms",
   "Ps Ch.": "112-113",
   "Proverbs": "Proverbs",
   "Prov Ch.": 16
 },
 {
   "Week": 115,
   "NT Book": "Luke",
   "NT Ch.": "21-24",
   "OT Book": "Job",
   "OT Ch.": "27-31",
   "Psalms": "Psalms",
   "Ps Ch.": "114-115",
   "Proverbs": "Proverbs",
   "Prov Ch.": 17
 },
 {
   "Week": 116,
   "NT Book": "1 Timothy",
   "NT Ch.": "",
   "OT Book": "Job",
   "OT Ch.": "32-34",
   "Psalms": "Psalms",
   "Ps Ch.": "116-118",
   "Proverbs": "Proverbs",
   "Prov Ch.": 18
 },
 {
   "Week": 117,
   "NT Book": "Hebrews",
   "NT Ch.": "1-4",
   "OT Book": "Job",
   "OT Ch.": "35-37",
   "Psalms": "Psalms",
   "Ps Ch.": "119-120",
   "Proverbs": "Proverbs",
   "Prov Ch.": 19
 },
 {
   "Week": 118,
   "NT Book": "Hebrews",
   "NT Ch.": "5-8",
   "OT Book": "Job",
   "OT Ch.": "38-40",
   "Psalms": "Psalms",
   "Ps Ch.": "121-122",
   "Proverbs": "Proverbs",
   "Prov Ch.": 20
 },
 {
   "Week": 119,
   "NT Book": "Hebrews",
   "NT Ch.": "9-13",
   "OT Book": "Job",
   "OT Ch.": "41-42",
   "Psalms": "Psalms",
   "Ps Ch.": "123-125",
   "Proverbs": "Proverbs",
   "Prov Ch.": 21
 },
 {
   "Week": 120,
   "NT Book": "2 Timothy",
   "NT Ch.": "",
   "OT Book": "Ecclesiastes",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "126-127",
   "Proverbs": "Proverbs",
   "Prov Ch.": 22
 },
 {
   "Week": 121,
   "NT Book": "Titus",
   "NT Ch.": "",
   "OT Book": "Ecclesiastes",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "128-129",
   "Proverbs": "Proverbs",
   "Prov Ch.": 23
 },
 {
   "Week": 122,
   "NT Book": "Revelation",
   "NT Ch.": "1-5",
   "OT Book": "Ecclesiastes",
   "OT Ch.": "9-12",
   "Psalms": "Psalms",
   "Ps Ch.": "130-132",
   "Proverbs": "Proverbs",
   "Prov Ch.": 24
 },
 {
   "Week": 123,
   "NT Book": "Revelation",
   "NT Ch.": "6-9",
   "OT Book": "Song of Solomon",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "133-134",
   "Proverbs": "Proverbs",
   "Prov Ch.": 25
 },
 {
   "Week": 124,
   "NT Book": "Revelation",
   "NT Ch.": "10-14",
   "OT Book": "Song of Solomon",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "135-136",
   "Proverbs": "Proverbs",
   "Prov Ch.": 26
 },
 {
   "Week": 125,
   "NT Book": "Revelation",
   "NT Ch.": "15-18",
   "OT Book": "Isaiah",
   "OT Ch.": "1-6",
   "Psalms": "Psalms",
   "Ps Ch.": "137-139",
   "Proverbs": "Proverbs",
   "Prov Ch.": 27
 },
 {
   "Week": 126,
   "NT Book": "Revelation",
   "NT Ch.": "19-22",
   "OT Book": "Isaiah",
   "OT Ch.": "7-12",
   "Psalms": "Psalms",
   "Ps Ch.": "140-141",
   "Proverbs": "Proverbs",
   "Prov Ch.": 28
 },
 {
   "Week": 127,
   "NT Book": "1 Peter",
   "NT Ch.": "",
   "OT Book": "Isaiah",
   "OT Ch.": "13-18",
   "Psalms": "Psalms",
   "Ps Ch.": "142-143",
   "Proverbs": "Proverbs",
   "Prov Ch.": 29
 },
 {
   "Week": 128,
   "NT Book": "Philemon",
   "NT Ch.": "",
   "OT Book": "Isaiah",
   "OT Ch.": "19-23",
   "Psalms": "Psalms",
   "Ps Ch.": "144-145",
   "Proverbs": "Proverbs",
   "Prov Ch.": 30
 },
 {
   "Week": 129,
   "NT Book": "2 Peter",
   "NT Ch.": "",
   "OT Book": "Isaiah",
   "OT Ch.": "24-27",
   "Psalms": "Psalms",
   "Ps Ch.": "146-148",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 130,
   "NT Book": "Jude",
   "NT Ch.": "",
   "OT Book": "Isaiah",
   "OT Ch.": "28-31",
   "Psalms": "Psalms",
   "Ps Ch.": "149-150",
   "Proverbs": "Proverbs",
   "Prov Ch.": 31
 },
 {
   "Week": 131,
   "NT Book": "1 John",
   "NT Ch.": "",
   "OT Book": "Isaiah",
   "OT Ch.": "32-35",
   "Psalms": "Psalms",
   "Ps Ch.": "1-2",
   "Proverbs": "Proverbs",
   "Prov Ch.": 1
 },
 {
   "Week": 132,
   "NT Book": "John",
   "NT Ch.": "1-4",
   "OT Book": "Isaiah",
   "OT Ch.": "36-39",
   "Psalms": "Psalms",
   "Ps Ch.": "3-4",
   "Proverbs": "Proverbs",
   "Prov Ch.": 2
 },
 {
   "Week": 133,
   "NT Book": "John",
   "NT Ch.": "5-8",
   "OT Book": "Isaiah",
   "OT Ch.": "40-44",
   "Psalms": "Psalms",
   "Ps Ch.": "5-7",
   "Proverbs": "Proverbs",
   "Prov Ch.": 3
 },
 {
   "Week": 134,
   "NT Book": "John",
   "NT Ch.": "9-12",
   "OT Book": "Isaiah",
   "OT Ch.": "45-48",
   "Psalms": "Psalms",
   "Ps Ch.": "8-9",
   "Proverbs": "Proverbs",
   "Prov Ch.": 4
 },
 {
   "Week": 135,
   "NT Book": "John",
   "NT Ch.": "13-17",
   "OT Book": "Isaiah",
   "OT Ch.": "49-53",
   "Psalms": "Psalms",
   "Ps Ch.": "10-11",
   "Proverbs": "Proverbs",
   "Prov Ch.": 5
 },
 {
   "Week": 136,
   "NT Book": "John",
   "NT Ch.": "18-21",
   "OT Book": "Isaiah",
   "OT Ch.": "54-57",
   "Psalms": "Psalms",
   "Ps Ch.": "12-14",
   "Proverbs": "Proverbs",
   "Prov Ch.": 6
 },
 {
   "Week": 137,
   "NT Book": "Philippians",
   "NT Ch.": "",
   "OT Book": "Isaiah",
   "OT Ch.": "58-62",
   "Psalms": "Psalms",
   "Ps Ch.": "15-16",
   "Proverbs": "Proverbs",
   "Prov Ch.": 7
 },
 {
   "Week": 138,
   "NT Book": "Matthew",
   "NT Ch.": "1-4",
   "OT Book": "Isaiah",
   "OT Ch.": "63-66",
   "Psalms": "Psalms",
   "Ps Ch.": "17-18",
   "Proverbs": "Proverbs",
   "Prov Ch.": 8
 },
 {
   "Week": 139,
   "NT Book": "Matthew",
   "NT Ch.": "5-8",
   "OT Book": "Jeremiah",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "19-21",
   "Proverbs": "Proverbs",
   "Prov Ch.": 9
 },
 {
   "Week": 140,
   "NT Book": "Matthew",
   "NT Ch.": "9-12",
   "OT Book": "Jeremiah",
   "OT Ch.": "5-9",
   "Psalms": "Psalms",
   "Ps Ch.": "22-23",
   "Proverbs": "Proverbs",
   "Prov Ch.": 10
 },
 {
   "Week": 141,
   "NT Book": "Matthew",
   "NT Ch.": "13-16",
   "OT Book": "Jeremiah",
   "OT Ch.": "10-13",
   "Psalms": "Psalms",
   "Ps Ch.": "24-25",
   "Proverbs": "Proverbs",
   "Prov Ch.": 11
 },
 {
   "Week": 142,
   "NT Book": "Matthew",
   "NT Ch.": "17-20",
   "OT Book": "Jeremiah",
   "OT Ch.": "14-17",
   "Psalms": "Psalms",
   "Ps Ch.": "26-28",
   "Proverbs": "Proverbs",
   "Prov Ch.": 12
 },
 {
   "Week": 143,
   "NT Book": "Matthew",
   "NT Ch.": "21-24",
   "OT Book": "Jeremiah",
   "OT Ch.": "18-22",
   "Psalms": "Psalms",
   "Ps Ch.": "29-30",
   "Proverbs": "Proverbs",
   "Prov Ch.": 13
 },
 {
   "Week": 144,
   "NT Book": "Matthew",
   "NT Ch.": "25-28",
   "OT Book": "Jeremiah",
   "OT Ch.": "23-25",
   "Psalms": "Psalms",
   "Ps Ch.": "31-32",
   "Proverbs": "Proverbs",
   "Prov Ch.": 14
 },
 {
   "Week": 145,
   "NT Book": "Colossians",
   "NT Ch.": "",
   "OT Book": "Jeremiah",
   "OT Ch.": "26-29",
   "Psalms": "Psalms",
   "Ps Ch.": "33-35",
   "Proverbs": "Proverbs",
   "Prov Ch.": 15
 },
 {
   "Week": 146,
   "NT Book": "Acts",
   "NT Ch.": "1-4",
   "OT Book": "Jeremiah",
   "OT Ch.": "30-33",
   "Psalms": "Psalms",
   "Ps Ch.": "36-37",
   "Proverbs": "Proverbs",
   "Prov Ch.": 16
 },
 {
   "Week": 147,
   "NT Book": "Acts",
   "NT Ch.": "5-8",
   "OT Book": "Jeremiah",
   "OT Ch.": "34-37",
   "Psalms": "Psalms",
   "Ps Ch.": "38-39",
   "Proverbs": "Proverbs",
   "Prov Ch.": 17
 },
 {
   "Week": 148,
   "NT Book": "Acts",
   "NT Ch.": "9-12",
   "OT Book": "Jeremiah",
   "OT Ch.": "38-42",
   "Psalms": "Psalms",
   "Ps Ch.": "40-42",
   "Proverbs": "Proverbs",
   "Prov Ch.": 18
 },
 {
   "Week": 149,
   "NT Book": "Acts",
   "NT Ch.": "13-16",
   "OT Book": "Jeremiah",
   "OT Ch.": "43-45",
   "Psalms": "Psalms",
   "Ps Ch.": "43-44",
   "Proverbs": "Proverbs",
   "Prov Ch.": 19
 },
 {
   "Week": 150,
   "NT Book": "Acts",
   "NT Ch.": "17-20",
   "OT Book": "Jeremiah",
   "OT Ch.": "46-49",
   "Psalms": "Psalms",
   "Ps Ch.": "45-46",
   "Proverbs": "Proverbs",
   "Prov Ch.": 20
 },
 {
   "Week": 151,
   "NT Book": "Acts",
   "NT Ch.": "21-24",
   "OT Book": "Jeremiah",
   "OT Ch.": "50-52",
   "Psalms": "Psalms",
   "Ps Ch.": "47-49",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 152,
   "NT Book": "Acts",
   "NT Ch.": "25-28",
   "OT Book": "Lamentations",
   "OT Ch.": "1",
   "Psalms": "Psalms",
   "Ps Ch.": "50-51",
   "Proverbs": "Proverbs",
   "Prov Ch.": 21
 },
 {
   "Week": 153,
   "NT Book": "2 John",
   "NT Ch.": "",
   "OT Book": "Lamentations",
   "OT Ch.": "2",
   "Psalms": "Psalms",
   "Ps Ch.": "52-53",
   "Proverbs": "Proverbs",
   "Prov Ch.": 22
 },
 {
   "Week": 154,
   "NT Book": "Galatians",
   "NT Ch.": "",
   "OT Book": "Lamentations",
   "OT Ch.": "3",
   "Psalms": "Psalms",
   "Ps Ch.": "54-56",
   "Proverbs": "Proverbs",
   "Prov Ch.": 23
 },
 {
   "Week": 155,
   "NT Book": "3 John",
   "NT Ch.": "",
   "OT Book": "Lamentations",
   "OT Ch.": "4",
   "Psalms": "Psalms",
   "Ps Ch.": "57-58",
   "Proverbs": "Proverbs",
   "Prov Ch.": 24
 },
 {
   "Week": 156,
   "NT Book": "Romans",
   "NT Ch.": "1-4",
   "OT Book": "Lamentations",
   "OT Ch.": "5",
   "Psalms": "Psalms",
   "Ps Ch.": "59-60",
   "Proverbs": "Proverbs",
   "Prov Ch.": 25
 },
 {
   "Week": 157,
   "NT Book": "Romans",
   "NT Ch.": "5-8",
   "OT Book": "Ezekiel",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "61-63",
   "Proverbs": "Proverbs",
   "Prov Ch.": 26
 },
 {
   "Week": 158,
   "NT Book": "Romans",
   "NT Ch.": "9-12",
   "OT Book": "Ezekiel",
   "OT Ch.": "4-7",
   "Psalms": "Psalms",
   "Ps Ch.": "64-65",
   "Proverbs": "Proverbs",
   "Prov Ch.": 27
 },
 {
   "Week": 159,
   "NT Book": "Romans",
   "NT Ch.": "13-16",
   "OT Book": "Ezekiel",
   "OT Ch.": "8-11",
   "Psalms": "Psalms",
   "Ps Ch.": "66-67",
   "Proverbs": "Proverbs",
   "Prov Ch.": 28
 },
 {
   "Week": 160,
   "NT Book": "Ephesians",
   "NT Ch.": "",
   "OT Book": "Ezekiel",
   "OT Ch.": "12-15",
   "Psalms": "Psalms",
   "Ps Ch.": "68-70",
   "Proverbs": "Proverbs",
   "Prov Ch.": 29
 },
 {
   "Week": 161,
   "NT Book": "Mark",
   "NT Ch.": "1-4",
   "OT Book": "Ezekiel",
   "OT Ch.": "16-19",
   "Psalms": "Psalms",
   "Ps Ch.": "71-72",
   "Proverbs": "Proverbs",
   "Prov Ch.": 30
 },
 {
   "Week": 162,
   "NT Book": "Mark",
   "NT Ch.": "5-8",
   "OT Book": "Ezekiel",
   "OT Ch.": "20-24",
   "Psalms": "Psalms",
   "Ps Ch.": "73-74",
   "Proverbs": "Proverbs",
   "Prov Ch.": 31
 },
 {
   "Week": 163,
   "NT Book": "Mark",
   "NT Ch.": "9-12",
   "OT Book": "Ezekiel",
   "OT Ch.": "25-28",
   "Psalms": "Psalms",
   "Ps Ch.": "75-76",
   "Proverbs": "Proverbs",
   "Prov Ch.": 1
 },
 {
   "Week": 164,
   "NT Book": "Mark",
   "NT Ch.": "13-16",
   "OT Book": "Ezekiel",
   "OT Ch.": "29-32",
   "Psalms": "Psalms",
   "Ps Ch.": "77-78",
   "Proverbs": "Proverbs",
   "Prov Ch.": 2
 },
 {
   "Week": 165,
   "NT Book": "James",
   "NT Ch.": "",
   "OT Book": "Ezekiel",
   "OT Ch.": "33-36",
   "Psalms": "Psalms",
   "Ps Ch.": "79-80",
   "Proverbs": "Proverbs",
   "Prov Ch.": 3
 },
 {
   "Week": 166,
   "NT Book": "1 Corinthians",
   "NT Ch.": "1-4",
   "OT Book": "Ezekiel",
   "OT Ch.": "37-39",
   "Psalms": "Psalms",
   "Ps Ch.": "81-83",
   "Proverbs": "Proverbs",
   "Prov Ch.": 4
 },
 {
   "Week": 167,
   "NT Book": "1 Corinthians",
   "NT Ch.": "5-8",
   "OT Book": "Ezekiel",
   "OT Ch.": "40-43",
   "Psalms": "Psalms",
   "Ps Ch.": "84-85",
   "Proverbs": "Proverbs",
   "Prov Ch.": 5
 },
 {
   "Week": 168,
   "NT Book": "1 Corinthians",
   "NT Ch.": "9-12",
   "OT Book": "Ezekiel",
   "OT Ch.": "44-48",
   "Psalms": "Psalms",
   "Ps Ch.": "86-87",
   "Proverbs": "Proverbs",
   "Prov Ch.": 6
 },
 {
   "Week": 169,
   "NT Book": "1 Corinthians",
   "NT Ch.": "13-16",
   "OT Book": "Daniel",
   "OT Ch.": "1-2",
   "Psalms": "Psalms",
   "Ps Ch.": "88-90",
   "Proverbs": "Proverbs",
   "Prov Ch.": 7
 },
 {
   "Week": 170,
   "NT Book": "1 Thessalonians",
   "NT Ch.": "",
   "OT Book": "Daniel",
   "OT Ch.": "3-4",
   "Psalms": "Psalms",
   "Ps Ch.": "91-92",
   "Proverbs": "Proverbs",
   "Prov Ch.": 8
 },
 {
   "Week": 171,
   "NT Book": "2 Corinthians",
   "NT Ch.": "1-4",
   "OT Book": "Daniel",
   "OT Ch.": "5-6",
   "Psalms": "Psalms",
   "Ps Ch.": "93-94",
   "Proverbs": "Proverbs",
   "Prov Ch.": 9
 },
 {
   "Week": 172,
   "NT Book": "2 Corinthians",
   "NT Ch.": "5-9",
   "OT Book": "Daniel",
   "OT Ch.": "7-9",
   "Psalms": "Psalms",
   "Ps Ch.": "95-97",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 173,
   "NT Book": "2 Corinthians",
   "NT Ch.": "10-13",
   "OT Book": "Daniel",
   "OT Ch.": "10-12",
   "Psalms": "Psalms",
   "Ps Ch.": "98-99",
   "Proverbs": "Proverbs",
   "Prov Ch.": 10
 },
 {
   "Week": 174,
   "NT Book": "2 Thessalonians",
   "NT Ch.": "",
   "OT Book": "Hosea",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "100-101",
   "Proverbs": "Proverbs",
   "Prov Ch.": 11
 },
 {
   "Week": 175,
   "NT Book": "Luke",
   "NT Ch.": "1-4",
   "OT Book": "Hosea",
   "OT Ch.": "4-8",
   "Psalms": "Psalms",
   "Ps Ch.": "102-104",
   "Proverbs": "Proverbs",
   "Prov Ch.": 12
 },
 {
   "Week": 176,
   "NT Book": "Luke",
   "NT Ch.": "5-8",
   "OT Book": "Hosea",
   "OT Ch.": "9-14",
   "Psalms": "Psalms",
   "Ps Ch.": "105-106",
   "Proverbs": "Proverbs",
   "Prov Ch.": 13
 },
 {
   "Week": 177,
   "NT Book": "Luke",
   "NT Ch.": "9-12",
   "OT Book": "Joel",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "107-108",
   "Proverbs": "Proverbs",
   "Prov Ch.": 14
 },
 {
   "Week": 178,
   "NT Book": "Luke",
   "NT Ch.": "13-16",
   "OT Book": "Amos",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "109-111",
   "Proverbs": "Proverbs",
   "Prov Ch.": 15
 },
 {
   "Week": 179,
   "NT Book": "Luke",
   "NT Ch.": "17-20",
   "OT Book": "Amos",
   "OT Ch.": "4-6",
   "Psalms": "Psalms",
   "Ps Ch.": "112-113",
   "Proverbs": "Proverbs",
   "Prov Ch.": 16
 },
 {
   "Week": 180,
   "NT Book": "Luke",
   "NT Ch.": "21-24",
   "OT Book": "Amos",
   "OT Ch.": "7-9",
   "Psalms": "Psalms",
   "Ps Ch.": "114-115",
   "Proverbs": "Proverbs",
   "Prov Ch.": 17
 },
 {
   "Week": 181,
   "NT Book": "1 Timothy",
   "NT Ch.": "",
   "OT Book": "Obadiah",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "116-118",
   "Proverbs": "Proverbs",
   "Prov Ch.": 18
 },
 {
   "Week": 182,
   "NT Book": "Hebrews",
   "NT Ch.": "1-4",
   "OT Book": "Jonah",
   "OT Ch.": "1-2",
   "Psalms": "Psalms",
   "Ps Ch.": "119-120",
   "Proverbs": "Proverbs",
   "Prov Ch.": 19
 },
 {
   "Week": 183,
   "NT Book": "Hebrews",
   "NT Ch.": "5-8",
   "OT Book": "Jonah",
   "OT Ch.": "3-4",
   "Psalms": "Psalms",
   "Ps Ch.": "121-122",
   "Proverbs": "Proverbs",
   "Prov Ch.": 20
 },
 {
   "Week": 184,
   "NT Book": "Hebrews",
   "NT Ch.": "9-13",
   "OT Book": "Micah",
   "OT Ch.": "1-3",
   "Psalms": "Psalms",
   "Ps Ch.": "123-125",
   "Proverbs": "Proverbs",
   "Prov Ch.": 21
 },
 {
   "Week": 185,
   "NT Book": "2 Timothy",
   "NT Ch.": "",
   "OT Book": "Micah",
   "OT Ch.": "4-5",
   "Psalms": "Psalms",
   "Ps Ch.": "126-127",
   "Proverbs": "Proverbs",
   "Prov Ch.": 22
 },
 {
   "Week": 186,
   "NT Book": "Titus",
   "NT Ch.": "",
   "OT Book": "Micah",
   "OT Ch.": "6-7",
   "Psalms": "Psalms",
   "Ps Ch.": "128-129",
   "Proverbs": "Proverbs",
   "Prov Ch.": 23
 },
 {
   "Week": 187,
   "NT Book": "Revelation",
   "NT Ch.": "1-5",
   "OT Book": "Nahum",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "130-132",
   "Proverbs": "Proverbs",
   "Prov Ch.": 24
 },
 {
   "Week": 188,
   "NT Book": "Revelation",
   "NT Ch.": "6-9",
   "OT Book": "Habakkuk",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "133-134",
   "Proverbs": "Proverbs",
   "Prov Ch.": 25
 },
 {
   "Week": 189,
   "NT Book": "Revelation",
   "NT Ch.": "10-14",
   "OT Book": "Zephaniah",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "135-136",
   "Proverbs": "Proverbs",
   "Prov Ch.": 26
 },
 {
   "Week": 190,
   "NT Book": "Revelation",
   "NT Ch.": "15-18",
   "OT Book": "Haggai",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "137-139",
   "Proverbs": "Proverbs",
   "Prov Ch.": 27
 },
 {
   "Week": 191,
   "NT Book": "Revelation",
   "NT Ch.": "19-22",
   "OT Book": "Zechariah",
   "OT Ch.": "1-4",
   "Psalms": "Psalms",
   "Ps Ch.": "140-141",
   "Proverbs": "Proverbs",
   "Prov Ch.": 28
 },
 {
   "Week": 192,
   "NT Book": "1 Peter",
   "NT Ch.": "",
   "OT Book": "Zechariah",
   "OT Ch.": "5-8",
   "Psalms": "Psalms",
   "Ps Ch.": "142-143",
   "Proverbs": "Proverbs",
   "Prov Ch.": 29
 },
 {
   "Week": 193,
   "NT Book": "Philemon",
   "NT Ch.": "",
   "OT Book": "Zechariah",
   "OT Ch.": "9-11",
   "Psalms": "Psalms",
   "Ps Ch.": "144-145",
   "Proverbs": "Proverbs",
   "Prov Ch.": 30
 },
 {
   "Week": 194,
   "NT Book": "2 Peter",
   "NT Ch.": "",
   "OT Book": "Zechariah",
   "OT Ch.": "12-14",
   "Psalms": "Psalms",
   "Ps Ch.": "146-148",
   "Proverbs": "",
   "Prov Ch.": null
 },
 {
   "Week": 195,
   "NT Book": "Jude",
   "NT Ch.": "",
   "OT Book": "Malachi",
   "OT Ch.": "",
   "Psalms": "Psalms",
   "Ps Ch.": "149-150",
   "Proverbs": "Proverbs",
   "Prov Ch.": 31
 }
]